### ISSUE TITLE
Final tweaks

### ISSUE THREAD

**Issue by rufuspollock** [datahq/datapackage-normalize-js#2]
* [x] Remove lodash (try just using simple operators) - and update package.json
* [x] rename index.js to normalize.js
* [x] Make this a script
  * [x] add #!/usr/bin/env node at top
  * [x] Run normalize
  * [x] Make normalize.js executable

```
node normalize.js path/to/datapackage.json
// or even better ./normalize.js path/to/datapackage.json

prints out updated dp stdout
```

**Comment by Mikanebu** [comment]
FIXED, now normalize.js is executable script, updated `readme.md`
